### PR TITLE
refactor: export `createLanguageServiceDefaults` and `yamlDefaults`

### LINKED ISSUE #171: Why `createLanguageServiceDefaults` is exported, but `yamlDefaults` is not?
As title.

I want to set `schema` dynamically but get previous `yamlDefaults`.

### PR DESCRIPTION
**Pull request by JounQin**
close #171

### CODE REVIEW

**Comment by remcohaszing** [comment]
Thanks!

**Comment by JounQin** [comment]
@remcohaszing Thanks for merging, any chance to release an alpha version?

**Comment by remcohaszing** [comment]
Sure! Just released version 4.0.0-alpha.3

**Comment by JounQin** [comment]
Thanks again for quick publishing. 🍺

**Pull request merged**
