### PR TITLE
Use monaco-marker-data-provider

### PR DESCRIPTION
**Pull request by remcohaszing**
This has been extracted from `monaco-yaml`, so it can be reused in other projects.

### CODE REVIEW

**Comment by domsew** [comment]
Have you considered to maintain `monaco-yaml` and `monaco-marker-data-provider` in single monorepo? (like for example `monaco-editor` and `monaco-editor-webpack-plugin`)

**Comment by remcohaszing** [comment]
> Have you considered to maintain `monaco-yaml` and `monaco-marker-data-provider` in single monorepo? (like for example `monaco-editor` and `monaco-editor-webpack-plugin`)

Is there any reason you’re asking this? I’ve extracted this to share some logic with [`monaco-tailwindcss`](https://github.com/remcohaszing/monaco-tailwindcss), [`appsemble`](https://github.com/appsemble/appsemble), and possibly some future projects.

**Comment by domsew** [comment]
`monaco-marker-data-provider` is a very small project. Monorepos are easier to maintain, manage or track changes. A lot of big projects have merged their subprojects into single monorepo. Thats why I asked. But I didn't know about `monaco-tailwindcss`. I understand you have reasons to split project.

**Comment by remcohaszing** [comment]
I appreciate your input, but I’m going to keep it in a separate repo. :)

**Pull request merged**
